version: "3.7"

services:
  app:
    build:
      context: ./
      target: production-build-stage
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URI=${MONGO_DB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  app_dev:
    build:
      context: ./
      target: development-build-stage
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URI=${MONGO_DB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
